---
- name: Deploy EC2 instance in AWS
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    region: us-east-1
    instance_type: t2.micro
    ami_id: ami-084568db4383264d4  
    user_data: |
      #!/bin/bash
      sudo apt-get update
      sudo apt  install docker.io -y
      sudo systemctl start docker
      sudo systemctl enable docker
      curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      chmod +x minikube
      mv minikube /usr/local/bin/
      minikube --version
      minikube start --driver=none
  tasks:       
    - name: Ensure correct Python interpreter
      ansible.builtin.command: /usr/bin/python3 -m pip install botocore boto3
      environment:
        ansible_python_interpreter: /usr/bin/python3
         
    - name: Create EC2 instance
      environment:
        ansible_python_interpreter: /usr/bin/python3
      amazon.aws.ec2_instance:
        region: us-east-1
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        user_data: "{{ user_data }}"
        wait: yes
        count: 1
      register: ec2
