---
- name: Deploy EC2 instance in AWS
  hosts: localhost
  connection: local
  gather_facts: False


  vars:
    region: us-east-1
    instance_type: t3.medium
    ami_id: ami-084568db4383264d4  
    TOKEN: "{{ TOKEN }}"
    user_data: |
      #!/bin/bash
      set -e  # Exit immediately if a command fails
      sudo apt-get update -y
      sudo apt-get install openjdk-17-jdk -y
      echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
      sudo apt-get install postgresql postgresql-contrib -y
      sudo systemctl enable postgresql
      sudo systemctl start postgresql
      sudo -u postgres psql <<EOF
      CREATE ROLE sonar WITH LOGIN ENCRYPTED PASSWORD 'akash1234';
      CREATE DATABASE sonarqube OWNER sonar;
      GRANT ALL PRIVILEGES ON DATABASE sonarqube TO sonar;
      EOF
      sudo apt-get install zip unzip -y
      sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.3.79811.zip -P /opt
      sudo unzip /opt/sonarqube-9.9.3.79811.zip -d /opt
      sudo mv /opt/sonarqube-9.9.3.79811 /opt/sonarqube
      sudo groupadd sonar
      sudo useradd -d /opt/sonarqube -g sonar sonar
      sudo chown -R sonar:sonar /opt/sonarqube
      sudo tee /opt/sonarqube/conf/sonar.properties <<EOF
      sonar.jdbc.username=sonar
      sonar.jdbc.password=akash1234
      sonar.jdbc.url=jdbc:postgresql://localhost:5432/sonarqube
      EOF
      sudo tee /etc/systemd/system/sonar.service <<EOF
      [Unit]
      Description=SonarQube service
      After=syslog.target network.target
      [Service]
      Type=forking
      User=sonar
      Group=sonar
      ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
      ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop
      StandardOutput=journal
      LimitNOFILE=131072
      LimitNPROC=8192
      Restart=always
      SuccessExitStatus=143
       
      [Install]
      WantedBy=multi-user.target
      EOF
      sudo systemctl enable sonar
      sudo systemctl start sonar
      sudo tee -a /etc/sysctl.conf <<EOF
      vm.max_map_count=262144
      fs.file-max=65536
      ulimit -n 131072
      ulimit -u 8192
      EOF
      sudo tee -a /etc/security/limits.conf <<EOF
      sonar soft nofile 131072
      sonar hard nofile 131072
      sonar soft nproc 8192
      sonar hard nproc 8192
      EOF
      sudo sysctl --system     
  tasks:       
    - name: Ensure correct Python interpreter
      ansible.builtin.command: /opt/pipx/venvs/ansible-core/bin/python -m pip install botocore boto3
      environment:
        ansible_python_interpreter: /opt/pipx/venvs/ansible-core/bin/python
         
    - name: Create EC2 instance
      environment:
        ansible_python_interpreter: /opt/pipx/venvs/ansible-core/bin/python
      amazon.aws.ec2_instance:
        region: us-east-1
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        user_data: "{{ user_data }}"
        tags: 
          Name: Sonarqube
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 30
              volume_type: gp3
        wait: yes
        count: 1
      register: ec2
