name: Python_deployment

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Build Application
        run: echo "Building..."
  
      - name: Set Deployment Environment
        run: |
          dsfdss

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Approvers  # Assign the dynamically selected environment
    steps:
      - name: Deploy Application
        run: echo "Deploying to $DEPLOY_ENV"
