name: Python_deployment

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variable
        run: echo "DEPLOY_ENV=Approvers" >> $GITHUB_ENV
        
      - name: Print Environment
        run: echo "Environment is $DEPLOY_ENV"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ vars.DEPLOY_ENV }}

    steps:
      - name: Print Environment
        run: echo "Deploying to $DEPLOY_ENV"
