name: Python_deployment

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Application
        run: echo "Building..."
  
      - name: Set Deployment Environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DEPLOY_ENV=Production" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENV=Staging" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ env.DEPLOY_ENV }}  # Assign the dynamically selected environment
    steps:
      - name: Deploy Application
        run: echo "Deploying to $DEPLOY_ENV"
