# This is a basic workflow to help you get started with Actions

name: Python_deployment

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Hello World
        run: |
          echo world
          echo "build=Approvers" >> $GITHUB_ENV
          
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: env.build
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Hello World
        run: |
          echo build world
          
