name: JSON File Update Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  manage_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create JSON file (if not exists)
        run: |
          if [ ! -f state.json ]; then
            echo '{}' > state.json
          fi
        shell: bash

      - name: Add key-value pair to JSON file
        run: |
          jq '. + {"stage1": "success"}' state.json > tmp.json && mv tmp.json state.json
        shell: bash

      - name: Update JSON file with new key-value pair
        run: |
          jq '. + {"stage2": "failed"}' state.json > tmp.json && mv tmp.json state.json
        shell: bash

      - name: Display JSON file contents
        run: cat state.json
        shell: bash