name: Stateful GitHub Actions Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      last_stage: ${{ steps.read-state.outputs.stage }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read last execution state
        id: read-state
        run: |
          if [ -f state.json ]; then
            LAST_STAGE=$(jq -r 'to_entries | map(select(.value == "failed")) | .[0].key' state.json)
            echo "Last failed stage: $LAST_STAGE"
            echo "stage=$LAST_STAGE" >> $GITHUB_ENV
          else
            echo "stage=none" >> $GITHUB_ENV
        shell: bash

  stage1:
    needs: initialize
    if: ${{ needs.initialize.outputs.last_stage == 'none' || needs.initialize.outputs.last_stage == 'stage1' }}
    runs-on: ubuntu-latest
    steps:
      - name: Execute Stage 1
        run: |
          echo "Running Stage 1"
          # Simulate failure
          exit 1
        shell: bash

      - name: Save failure state
        if: ${{ failure() }}
        run: |
          echo '{"stage1": "failed"}' > state.json
        shell: bash

      - name: Save success state
        if: ${{ success() }}
        run: |
          echo '{"stage1": "success"}' > state.json
        shell: bash

  stage2:
    needs: stage1
    if: ${{ needs.initialize.outputs.last_stage == 'stage2' }}
    runs-on: ubuntu-latest
    steps:
      - name: Execute Stage 2
        run: echo "Running Stage 2"
        shell: bash

      - name: Save success state
        run: |
          echo '{"stage2": "success"}' > state.json
        shell: bash

  stage3:
    needs: stage2
    runs-on: ubuntu-latest
    steps:
      - name: Execute Stage 3
        run: echo "Running Stage 3"
        shell: bash

      - name: Save success state
        run: |
          echo '{"stage3": "success"}' > state.json
        shell: bash